@startuml
class Personaje
class BombaNormal
class BombaRemota
class Temporizador
class Vida
class Credito
class BloqueDestructible
class BloqueIndestructible
class Bota
class Guante
class Puerta
class EnemigoBasico
class MiniJefe
class JefeFinal
class ModoJuego
class Explosion
class Calavera
class Mascota
class Nivel
class Mapa
class Invisibilidad
class TiempoExtra
class Item
class FireUp
class BombUp
class SpeedUp
class Heart
class Escudo
class EnemigoVolador
class EnemigoAvanzado
BombaNormal --|> Item
BombaRemota --|> Item
FireUp --|> Item
BombUp --|> Item
SpeedUp --|> Item
Heart --|> Item
Escudo --|> Item
Calavera --|> Item
Invisibilidad --|> Item
TiempoExtra --|> Item
Bota --|> Item
Guante --|> Item
EnemigoBasico --|> Personaje
MiniJefe --|> EnemigoBasico
JefeFinal --|> EnemigoBasico
EnemigoVolador --|> EnemigoBasico
EnemigoAvanzado --|> EnemigoBasico
Personaje *-- Vida
Personaje *-- BombaNormal
Personaje *-- BombaRemota
Personaje *-- Mascota
BombaNormal *-- Temporizador
BombaRemota *-- Temporizador
Nivel *-- Mapa
Nivel *-- Puerta
Nivel *-- BloqueDestructible
Nivel *-- BloqueIndestructible
Nivel *-- EnemigoBasico
Nivel *-- Item
Explosion *-- Temporizador
ModoJuego *-- Nivel
ModoJuego *-- Credito
Personaje o-- Item
Personaje o-- Explosion
Personaje o-- Puerta
BombaNormal o-- Explosion
BombaRemota o-- Explosion
Explosion o-- BloqueDestructible
Explosion o-- EnemigoBasico
Guante o-- BombaNormal
Guante o-- BombaRemota
Bota o-- SpeedUp
Mascota o-- Item
EnemigoBasico o-- Personaje
MiniJefe o-- Explosion
JefeFinal o-- Explosion

@enduml
